name: Test my application
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    name: Run Vitest tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test
